// Liste der deutschen Banken + PayPal + Wise für die Bank-Auswahl
export const GERMAN_BANKS = [
  "PayPal",
  "Wise (TransferWise)",
  "DKB",
  "Commerzbank",
  "Deutsche Bank",
  "Sparkasse",
  "Volksbank / Raiffeisenbank",
  "Postbank",
  "ING",
  "Comdirect",
  "1822direkt",
  "Norisbank",
  "DiBa (Direktbank)",
  "Consorsbank",
  "Santander",
  "Targobank",
  "Netbank",
  "GLS Bank",
  "EthikBank",
  "Triodos Bank",
  "N26",
  "Revolut",
  "Scalable Capital",
  "Trade Republic",
  "eToro",
  "Interactive Brokers",
  "Lynx Broker",
  "CAPITAL.COM",
  "Flatex",
  "Onvista Bank",
  "Fyrst (ehem. Solarbank)",
];

export const EUROPEAN_BANKS = [
  ...GERMAN_BANKS,
  "BNP Paribas",
  "Société Générale",
  "Crédit Agricole",
  "Lloyds Bank",
  "Barclays",
  "HSBC",
  "Santander (UK)",
  "ABN AMRO",
  "Rabobank",
  "ING Nederland",
  "SEB",
  "Swedbank",
  "Handelsbanken",
  "Danske Bank",
  "Nordea",
  "DNB",
  "CaixaBank",
  "BBVA",
  "Saberbank",
  "Raiffeisen Bank International",
  "Erste Bank",
  "UniCredit",
  "Intesa Sanpaolo",
];
