import 'dart:convert';
import 'dart:io';
import 'dart:typed_data';

import 'package:finanzgecko/constants.dart';
import 'package:finanzgecko/data/app_schema.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:image/image.dart' as img;

import '../tool/generate_demo_data.dart' show buildDemoBackup;
import '../tool/generate_icons.dart' show generateLinuxIcons, generateWindowsIcon, windowsIconSizes;

/// Runs (and thereby regenerates) the dev tooling as part of `flutter test`, so
/// the derived artifacts are always produced from their sources:
///   * demo/finanzgecko-demo.json  <- buildDemoBackup(), anchored to today
///   * icons/icon-512.png, -192.png <- the master PNG, resized
///   * windows/runner/resources/app_icon.ico <- the master PNG, multi-size
/// and validates the results. The macOS launcher-icons step stays a subprocess
/// (`dart run tool/generate_icons.dart`) — spawning it on every `flutter test`
/// would be slow and platform-specific, so it's not run here.
void main() {
  double r2(num v) => (v * 100).roundToDouble() / 100;
  String pkey(DateTime d) => '${d.year.toString().padLeft(4, '0')}-${d.month.toString().padLeft(2, '0')}';

  group('demo data (generated by flutter test)', () {
    final now = DateTime.now();
    final backup = buildDemoBackup(now: now);
    final accounts = (backup['accounts'] as List).cast<Map<String, dynamic>>();
    final balances = (backup['balances'] as List).cast<Map<String, dynamic>>();
    final subscriptions = (backup['subscriptions'] as List).cast<Map<String, dynamic>>();

    setUpAll(() {
      final file = File('demo/finanzgecko-demo.json');
      file.parent.createSync(recursive: true);
      file.writeAsStringSync(const JsonEncoder.withIndent('  ').convert(backup));
    });

    test('writes an importable demo file', () {
      final file = File('demo/finanzgecko-demo.json');
      expect(file.existsSync(), isTrue);
      final data = AppSchema.fromDynamic(jsonDecode(file.readAsStringSync()));
      expect(data, isNotNull);
      expect(data!.accounts, hasLength(6));
      expect(data.balances, hasLength(19 * 6));
      expect(data.assets, hasLength(3));
      expect(data.subscriptions, hasLength(8));
    });

    test('is anchored to the current month and spans 19 months', () {
      final periods = balances.map((b) => b['period'] as String).toSet().toList()..sort();
      expect(periods.length, 19);
      expect(periods.last, pkey(now));
    });

    test('every balance references an existing account', () {
      final ids = accounts.map((a) => a['id']).toSet();
      for (final b in balances) {
        expect(ids, contains(b['accountId']));
      }
    });

    test('amountBase equals amountOriginal x rate (rounded)', () {
      for (final b in balances) {
        expect(r2((b['amountOriginal'] as num) * (b['rate'] as num)), b['amountBase']);
      }
    });

    test('only valid domain values are used', () {
      final validIntervals = {for (final i in kSubscriptionIntervals) i.value};
      for (final a in accounts) {
        expect(kTags, contains(a['tag']));
        expect(kCurrencies, contains(a['currency']));
      }
      for (final s in subscriptions) {
        expect(validIntervals, contains(s['interval']));
      }
    });

    test('uses more than one currency (exercises the FX features)', () {
      expect(accounts.map((a) => a['currency']).toSet().length, greaterThan(1));
    });

    test('accounts carry no color and use known banks (color is derived on import)', () {
      for (final a in accounts) {
        expect(a.containsKey('color'), isFalse, reason: 'color is derived from the bank on import, not stored');
        final bank = a['bank'] as String;
        if (bank.isNotEmpty) {
          expect(isKnownBank(bank), isTrue, reason: 'demo bank "$bank" must exist in kBanks');
        }
      }
    });

    test('round-trips through export -> import', () {
      final reparsed = AppSchema.fromDynamic(AppSchema.fromDynamic(backup)!.toExportJson())!;
      expect(reparsed.balances, hasLength(19 * 6));
      expect(reparsed.subscriptions, hasLength(8));
    });
  });

  group('icons (regenerated by flutter test)', () {
    late List<String> written;
    late String windowsIcon;
    setUpAll(() {
      written = generateLinuxIcons();
      windowsIcon = generateWindowsIcon();
    });

    test('the 1024x1024 master icon exists and is a PNG', () {
      final file = File('assets/icon/icon.png');
      expect(file.existsSync(), isTrue);
      expect(file.readAsBytesSync().sublist(0, 8), [0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A]);
    });

    test('regenerates the Linux hicolor icons at the right sizes', () {
      expect(written, containsAll(['icons/icon-512.png', 'icons/icon-192.png']));
      for (final entry in {'icons/icon-512.png': 512, 'icons/icon-192.png': 192}.entries) {
        final file = File(entry.key);
        expect(file.existsSync(), isTrue);
        final decoded = img.decodePng(file.readAsBytesSync())!;
        expect(decoded.width, entry.value);
        expect(decoded.height, entry.value);
      }
    });

    test('regenerates the Windows .ico with all sizes embedded (not just 256px)', () {
      final bytes = File(windowsIcon).readAsBytesSync();
      // ICO directory: 6-byte header, then one 16-byte entry per frame; a
      // frame's width/height is stored as a single byte (0 means 256px).
      final frameCount = bytes.buffer.asByteData().getUint16(4, Endian.little);
      expect(frameCount, windowsIconSizes.length);
      final sizes = <int>[];
      for (var i = 0; i < frameCount; i++) {
        final w = bytes[6 + i * 16];
        sizes.add(w == 0 ? 256 : w);
      }
      expect(sizes, containsAll(windowsIconSizes));
    });
  });
}
